fix: do not type internal PiwaBadInputError
arhubi/piwa pull request #1
Opened 2023-01-10 15:46 UTC by qnp

- As this error is seen only in *runtime*, it is good to make it a custom error with class extension, but should not type the error which is returned by piwa because we will always have type mismatches, and it will not serve as a type check / type spell. Moreover, this error is fired only when the input is incorrect, which could appear in non-TS environments (or poorly typed ones).

2023-01-11 07:39 UTC, arhubi commented
I made a PR based on yours (as you're on a fork it's not handy to work on your branch) to tackle the error handling + typings issue : 
https://github.com/arhubi/piwa/pull/3

2023-01-12 06:49 UTC, arhubi requested changes

2023-01-12 06:49 UTC, arhubi commented on src/index.ts
> +    return { data: null, error: new PiwaBadInputError() as Err };
Unfortunately this is not true. If we pass a custom error as param type, it will probably not be a `PiwaBadInputError`, but the error type will only return the custom error type (hiding the `PiwaBadInputError` option). And anyway in a TS context the error will be hinted before the runtime..

I finally think considering `PiwaBadInputError` as a "normal" error is not a good choice. It would probably be better to consider it as a piwa usage error, and simply `throws` when function arguments are bad.

2023-01-12 14:57 UTC, qnp commented
Won't merge

2023-01-12 14:57 UTC, closed without merging